name: Run Crawler Script

on:
  schedule:
    - cron: '0 15 * * *' # 매일 자정 UTC 시간으로 설정, 한국시간 자정은 UTC 15시
  workflow_dispatch: # 수동으로 실행할 수 있는 옵션

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 원하는 Python 버전으로 변경

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager beautifulsoup4 mysql-connector-python psutil konlpy

      - name: Run crawler script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          python crawler_news_by_link.py
